### ISSUE TITLE
vFile beta task list

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#1878]
Testing (Perf/scale/feature stress)

  - [x] Modify deploy script to deploy vFile plugin on docker host: #1684 
  - [ ] Have CI testbed for vFile, and enable existing e2e test for vFile  to run in CI (Need Anup or Nirdesh to bring up the testbed in CI) #1776 
  - [x] Review current tests we have for vFile, and figure out new tests that need to be added:  #1806
  - [ ] Configure CI testbed setup with multi manager swarm cluster setup for failover testing #1682

----------------
Address correctness issues
  - [ ] Failed to mount vFile volume. Error: exit status 255 on Swarm master #1816 
  - [ ] Populate client list on mount and depopulate on unmount #1761 
  - [ ] Handle swarm node role change in vFile plugin https://github.com/vmware/docker-volume-vsphere/issues/1732
----------------
Document
- [ ] FAQs : Document why multi writer mode does not solve shared volume use case for all applications.  #1681 
- [ ] Customer configuration recommendation, based on the performance/stress testing result 
----------------
Misc(Fit and finish)
- [ ] vFile: Complete Docker certification to enable listing on Docker Store https://github.com/vmware/docker-volume-vsphere/issues/1777
- [ ] upgrade guide #1877 
- [ ] Containerize our own Samba server https://github.com/vmware/docker-volume-vsphere/issues/1729

**Comment by shuklanirdesh82** [comment]
This is Epic so adding `mustfix`
