### ISSUE TITLE
vFile plugin upgrade epic

### ISSUE THREAD

**Issue by luomiao** [vmware/docker-volume-vsphere#1918]
- [ ] Evaluate current upgrade steps

- [ ] Update userguide documentation with manual upgrade steps

- [ ] Code changes for hot upgrade

- [ ] CI/CD tests for upgrade
