### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#235]
- [x] Copyrights & License. Tracked in #234 
- [x] **Review and revise guidelines for contributing code, merge process, testing requirements**
- [ ] Cleanup [landing page](https://github.com/vmware/docker-vmdk-plugin/blob/master/README.md) (PM)
- [x] **Add Direct Download link [Download] users who don't want to clone and compile**
- [x] Establish means of communication (mailto:cna-storage@vmware.com)
  - [ ] ~~Setup Slack channel~~
  - [x] Public Mailing List cna-storage@vmware.com (mailman?) or Discourse(http://www.discourse.org/) 
- [ ] Branching Strategy (Discuss & document) - waiting for comments in email
- [ ] Code Cleanup
  - [ ] ~~Add function header comments. For reference, see [Engineering Manual](http://vmweb.vmware.com/~mts/WebSite/guide/programming/engman.html)~~
  - [x] Scan for TODOs. File git issues and reference them in code.
  - [ ] ~~Scan & replace tabs with spaces and \r with \n~~
  - [ ] Add code coverage - post TP
- [ ] ~~Describe pros/cons of https://github.com/vmware/ vs https://github.com/vmware/vsphere-flocker-driver and how it integrates with vsphere~~
- [ ] ~~Project code name?~~ Tracked in https://github.com/vmware/docker-vmdk-plugin/issues/254
- [ ] ~~Logo?~~
- [ ] Documentation:
  - [x] Add Installation and usage details to [README.md](https://github.com/vmware/docker-vmdk-plugin/blob/master/README.md)
  - [ ] Do we need user guide? (PM)
- [x] Setup contribution license agreement (CLA) signing process for non-VMware contributors
- [ ] Add reference to this repo from https://github.com/vmware/vsphere-flocker-driver  (PM)
- [ ] Inbound marketing 
  - [ ] VMware official release (PM) 
  - [ ] https://blogs.vmware.com/virtualblocks/  (PM or Dev)
  - [ ] http://blogs.vmware.com/cloudnative (PM) && https://twitter.com/cloudnativeapps (PM or Dev)
