### ISSUE TITLE
Docker 1.12 compatibility tracking

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#341]
Not adding links to avoid cross referencing issues to Docker repo until we go public.

- [ ] Add `Status` field to `VolumeDriver.Get` response (PR #21006)
- [ ] Mount/Unmount receives opaque ID (PR #21015)
- [ ] Support "shared" volume. Add `shared` `scope` to VolumeDriver.Capabilities (PR #22077)

**Comment by govint** [comment]
Update: None of these are available yet (till 1.12 is released) but we could develop at least the server and client side code till 1.12 is released.

1. Docker PR #21006 - provide a status of the volume.

On a Get() plugin needs to return a status of the volume, which may include whatever status that the plugin wishes to supply - create time options, attached status, attached-to-vm, created-by-vm.

ToDo:
Today plugin responds to Get() by doing list() to the server and returns the mountpoint for the specific volume. Since we maintain all volume meta-data on the server, we may need to add a "Get" request to the server to return this detail to the client.

2. Docker PR #22077 - Support a Capabilities() API in the plugin.

This API is called via the volume driver Scope() interface. Its optional. A plugin can support either "local" or "global" volumes (global - visible across a cluster). Used by cluster managers (for containers?) to decide whether volumes are available or not across a cluster.
Plugin can't support both scopes. If plugin doesn't support this method then the scope defaults to "local".

Todo:
Plugin client must be updated to include this API. Not sure if we want to say that we only support global or local volumes as we support both.

Will update on PR #21015.

**Comment by govint** [comment]
Pulled the current go-plugin-helper and its not updated to support the new API either. How do we plan to get this beta?

I'll create separate issues for the two features above two.

**Comment by govint** [comment]
Docker PR 21015

1.12 code has a new string ID passed on mount and unmount to match mount() and unmount() requests to the plugin. Docker is creating a unique ID per container thats using the same volume. All of the below are known to us, just noting it here info.

Todo:
a. The plugin needs to support the ID string on mount/unmount calls and remember the ID for each volume. Some thing like a insert into list and remove on mount/unmount calls with an ID.

**Comment by govint** [comment]
Following are the key considerations for this issue:

1. We want to make sure Docker Volume Plugin for vSphere doesn't break if customer upgrades to Docker engine to 1.12

With docker 1.12 we are able to run the basic set of create/list/inspect/rm/attach/detach work flows without any errors.

2. Can we update our plugin code to support 1.12 so that we don't have to make a release once 1.12 becomes available

Yes, we can do this up front as suggested in earlier udpates. Though seems close for beta release.

3. If we do (2) then will plugin contiue to work with older version of Docker Engine

Unlike what I read in the code, the plugin API itself isn't changing because the API gets a request structure as argument and hence API remains the same. Handling of new additions to the request structure is left to the plugin.

For PRs #22077 and #21006, it seems not critical to implement these.

For PR #21015 though, we may want to support opaque ID for mount and unmount requests to avoid the bugs that this PR handles.

**Comment by pdhamdhere** [comment]
Thanks @govint for confirming Docker Engine upgrade to 1.12 won't have issues with this plugin.

Let's address 1.12 features, forward/ backward plugin compatibility post Beta.

**Comment by govint** [comment]
Closing this issue as separate issues #524, #529 are tracking the individual docker 1.12 features. Will open a separate issue for tracking the unique ID for mount/unmount.
