### ISSUE TITLE
Redesign / Rework test infra

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#472]
Our current test infra ('make test-all' and CI) is comprise of python server-side tests, GO client-side tests, and Go end to end test which sometimes call .sh (e.g. refcnt_test.sh). Issue: 

- [x] It requires Docker config to accept TCP connection (tracked at #1011 )
- [x] it does not provide test coverage or lint coverage ( #404, #869 )
- [x] it's hard to add simple trivial things which can be done in scripts since test APIs/libs are not clearly defined
   Examples: we do not have some test automated due to this e.g.

Notes from @shuklanirdesh82: we have started implementing test library to reuse code while writing new automation tests so marking this as addressed.

- [x] multiple datastores test ( addressed via #957)
- [x] ESX failover test ( addressed via #957)
- [x] VM snapshot/vmotion test (tracked at #1012 and #1013 respectively)
- [x] scale/perf tests (tracked at #63)

  etc...

This Issue asks for a desgin/discussion and plan of record for reworked test infra and new test sets for GA. We may create other issues to address actual work 

//CC @pdhamdhere @kerneltime

**Comment by govint** [comment]
Also, the infra should allow easy addition of new tests. My suggestions are:

a. defining a template for a test script which is coded by who ever needs to add a test case. The script/code is dropped into the repository and is then picked up by the infra and included in a test run.

b. assign IDs for tests so we know what tests in a list have passed/failed.

c. Categorize the tests into groups so they can be run independently, developer may want to run a subset depending on what code they fix.

**Comment by kerneltime** [comment]
We have need for VMs that have been running over a long duration as well as VMs that get setup as new. https://github.com/vmware/docker-volume-vsphere/pull/584

**Comment by shuklanirdesh82** [comment]
> https://github.com/vmware/docker-volume-vsphere/issues/472#issuecomment-226411645

need to find out better test automation framework which satisfies all the requirement mentioned in the above comment. 

Note: keeping this issue open to address above comment.

> https://github.com/vmware/docker-volume-vsphere/issues/472#issue-160537235

separate issues are created to keep track of each action item so moving this issue in to ```future``` milestone.

**Comment by shuklanirdesh82** [comment]
new test framework integration task is done through #1246 so closing this Issue.
