### ISSUE TITLE
Improve test coverage by addressing test gaps for vSphere docker volume plugin

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#793]
This issue is focusing on adding more tests for plugin module.
- [ ] #743 (exercise volume operations from multiple endpoint)
- [x] #794 (create vSphere volume on newly created vm)
- [ ] #820 (update access option for the volume)

**Comment by tusharnt** [comment]
Individual issues are already filed for tracking.
